homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
]

jadwal/urls.py
from django.urls import path

from . import views

app_name = 'jadwal'

urlpatterns = [
    #path('', views.index, name='jadwal'),
    path('', views.jadwal_ku, name = 'jadwal'),
    path('<int:pk>/', views.delete, name = 'hapus'),
    path('detail/<int:pk>', views.detail, name='detail'),

    # dilanjutkan ...
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1'),
    # dilanjutkan ...
]

story5/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('jadwal/', include('jadwal.urls')),

]

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    nama_mata_kuliah = models.CharField(blank=False, max_length = 100)
    nama_dosen = models.CharField(blank=False, max_length=100)
    jumlah_sks = models.CharField(blank=False, max_length = 3)
    deskripsi_mata_kuliah = models.CharField(blank=False, max_length = 200)
    tahun_semester = models.CharField(blank=False, max_length = 50)
    ruang_kelas = models.CharField(blank=False, max_length = 100)
    

story1/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django import forms

class formulir(forms.Form):
    nama_mata_kuliah = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Mata Kuliah',
        'type' : 'text',
        'required' : True
    }))
    nama_dosen = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Dosen',
        'type' : 'text',
        'required' : True
    }))
    jumlah_sks = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah SKS',
        'type' : 'text',
        'required' : True
    }))
    deskripsi_mata_kuliah = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Deskripsi Mata Kuliah',
        'type' : 'text',
        'required' : True
    }))
    tahun_semester = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'ex: Gasal 2019/2020',
        'type' : 'text',
        'required' : True
    }))
    ruang_kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Lokasi Ruang Kelas',
        'type' : 'text',
        'required' : True
    }))

homepage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def blog(request):
    return render(request, 'blog.html')

def contact(request):
    return render(request, 'contact.html')

jadwal/views.py
from django.shortcuts import render, redirect
from . import forms,models

# Create your views here.
# def index(request):
#     return render(request, 'index.html')

def jadwal_ku(request):
    if(request.method == "POST"):
        context = forms.formulir(request.POST)
        if (context.is_valid()):
            context1 = models.Jadwal()
            context1.nama_mata_kuliah = context.cleaned_data["nama_mata_kuliah"]
            context1.nama_dosen = context.cleaned_data["nama_dosen"]
            context1.jumlah_sks = context.cleaned_data["jumlah_sks"]
            context1.deskripsi_mata_kuliah = context.cleaned_data["deskripsi_mata_kuliah"]
            context1.tahun_semester = context.cleaned_data["tahun_semester"]
            context1.ruang_kelas = context.cleaned_data["ruang_kelas"] 
            context1.save()
        return redirect("/jadwal")
    else:
        context = forms.formulir()
        context1 = models.Jadwal.objects.all()
        context_dictio = {
            'formulir' : context,
            'jadwal_ku' : context1
        }
    return render(request, 'index.html', context_dictio)
    

def delete(request, pk):
    if(request.method == "POST"):
        context = forms.formulir(request.POST)
        if(context.is_valid()):
            context1 = models.Jadwal()
            context1.nama_mata_kuliah = context.cleaned_data["nama_mata_kuliah"]
            context1.nama_dosen = context.cleaned_data["nama_dosen"]
            context1.jumlah_sks = context.cleaned_data["jumlah_sks"]
            context1.deskripsi_mata_kuliah = context.cleaned_data["deskripsi_mata_kuliah"]
            context1.tahun_semester = context.cleaned_data["tahun_semester"]
            context1.ruang_kelas = context.cleaned_data["ruang_kelas"] 
            context1.save()
        return redirect("/jadwal")
    else:
        models.Jadwal.objects.filter(pk = pk).delete()
        context = forms.formulir()
        context1 = models.Jadwal.objects.all()
        context_dictio = {
            'formulir' : context,
            'jadwal_ku' : context1
        }
        return render(request, 'index.html', context_dictio)

def detail(request, pk):
    models.Jadwal.objects.get(pk = pk)
    context = forms.formulir()
    context_dictio= {
        "detail" : context,
    }
    return render(request, 'detail.html', context_dictio)

story1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 'story1.html')

homepage/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>about.</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style2.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</head>
<body>
    {% include 'navbar.html' %}
    <br>
    <br>
    
    <div class="column">
    <div>
        <img src="{% static 'fotodidan.jpg' %}" height ="300">
    </div>
    </div>
    
    <div class="center2">
        <table style="width:70%">  
            <tr>
                <td><strong>Name :</strong></td>
                <td><b>Dzaky Zaydan</b></td>
            </tr>
            <tr>
                <td><strong>NPM :</strong></td>
                <td><b>1906304181</b></td>
            </tr>
            <tr>
                <td><strong>Major :</strong></td>
                <td><b>Information System</b></td>
            </tr>
            <tr>
                <td><strong>Student of  :</strong></td>
                <td><b>Fasilkom UI - 2019 </b></a></td>
            </tr>
            <tr>
                <td><strong>Hobby   :</strong></td>
                <td><b>Drawing and Sports</b></a></td>
            </tr>
        </table>
        <br>
        <br>
        <table style="width:70%">
            <tr>
                <td><strong>SDS Kartika X-7</strong></td>
                <td><b>2007 - 2013</b></td>
            </tr>
            <tr>
                <td><strong>SMP Negeri 117 Jakarta</strong></td>
                <td><b>2013 - 2016</b></td>
            </tr>
            <tr>
                <td><strong>SMA Negeri 61 Jakarta </strong></td>
                <td><b>2016 - 2019</b></td>
            </tr>
            <tr>
                <td><strong>University of Indonesia</strong></td>
                <td><b>2019 - present</b></i></td>
            </tr>
        </table>
    </div>

    <div class="center">
        <h2>A person who likes listening to piano songs and ballads!</h2>
    </div>

    <div class="footer">
        <p>Copyright @ 2020 Dzaky</p>
      </div>
</body>
</html>

homepage/templates/blog.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>about.</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style3.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</head>
<body>
    {% include 'navbar.html' %}
    <br>
    <br>

    <div>
        <img src="{% static 'fotokeluarga.jpg' %}" width="320" height ="261">
        <img src="{% static 'futsal.jpg' %}" width="300" height ="261">
        <img src="{% static 'temen.jpg' %}" width="320" height ="261">
    </div>
    
    <div class="footer">
        <p>Copyright @ 2020 Dzaky</p>
      </div>
</body>
</html>

homepage/templates/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>about.</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</head>
<body>
    {% include 'navbar.html' %}
    <div class="center">
        <a rel="noopener noreferrer" href="https://www.linkedin.com/in/dzaky-zaydan-49bb681a2/" target="_blank">
        <img src="https://www.iconfinder.com/data/icons/social-round-corner/512/linkdin__social_media_logo-512.png" width="70" height="70">
        </a>
        <a rel="noopener noreferrer" href="https://www.facebook.com/dzaky.zaydan" target="_blank">
        <img src="https://www.iconfinder.com/data/icons/transparent-on-dark-grey/500/icon-02-512.png" width="70" height="70">
        </a>
        <a rel="noopener noreferrer" href="https://twitter.com/Dzaky_DZ" target="_blank">
        <img src="https://www.iconfinder.com/data/icons/transparent-on-dark-grey/500/icon-03-512.png" width="70" height="70">
        </a>
        <a rel="noopener noreferrer" href="https://www.instagram.com/dzakyzaydan/" target="_blank">
        <img src="https://www.iconfinder.com/data/icons/transparent-on-dark-grey/500/icon-04-512.png" width="70" height="70" >
        </a>
    </div>
    <div class="footer">
        <p>Copyright @ 2020 Dzaky</p>
      </div>
</body>
</html>

homepage/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>home.</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</head>
<body>
    {% include 'navbar.html' %}
    <div class="center">
        <h2>DZAKY ZAYDAN</h2>
        <hr size="2px" width="60%" color="black">
        <h2>to be energic, act energic.</h2>
    </div>

    <div class="footer">
        <p>Copyright @ 2020 Dzaky</p>
      </div>
</body>
</html>

homepage/templates/navbar.html
<html>
    <nav class="navbar navbar-expand-sm navbar-light">
        <a class="navbar-brand" href="{% url 'homepage:home' %}">Dzaky Zaydan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">   
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'homepage:home' %}">home.</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'homepage:about' %}">about.</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'homepage:blog' %}">blog.</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'homepage:contact' %}">contact.</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'story1:story1' %}">story1.</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'jadwal:jadwal' %}">schedule.</a>
                </li>
            </ul>
        </div>  
    </nav>
</html>

jadwal/templates/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>schedule.</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style2.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>

<body>
    {% include 'navbar.html' %}
    <section class="cekjadwal" id="cekjadwal">
        <div class="table-responsive" id="Table">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Nama Mata Kuliah</th>
                        <th scope="col">Nama Dosen</th>
                        <th scope="col">Jumlah SKS</th>
                        <th scope="col">Deskripsi Mata Kuliah</th>
                        <th scope="col">Tahun Semester</th>
                        <th scope="col">Ruang Kelas</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                {% for i in jadwal_ku %}
                <tbody>
                    <tr>
                        <td>{{i.nama_mata_kuliah}}</td>
                        <td>{{i.nama_dosen}}</td>
                        <td>{{i.jumlah_sks}}</td>
                        <td>{{i.deskripsi_mata_kuliah}}</td>
                        <td>{{i.tahun_semester}}</td>
                        <td>{{i.ruang_kelas}}</td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
    </section>
    <a href="{% url 'jadwal:jadwal' %}" class="btn btn-default btn-lg"><u>BACK</u></a>
    <div class="footer">
        <p>Copyright @ 2020 Dzaky</p>
      </div>
</body>
</html>

jadwal/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>schedule.</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style2.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>

<body>
    {% include 'navbar.html' %}
    <section class="inputJadwal" id="inputJadwal">
        <div class="container pt-5 pb-3 justify-content">
            <div class="row pt-5">
                <div class="col-md-4">
                    <div class="card text-white bg-primary mb-3 pb-3 text-center" style="max-width: 18rem;">
                        <div class="card-body">
                          <h5 class="card-title"><h2><b>Isi Jadwal</b></h2></h5>
                          <p class="card-text"><i>Pengisian jadwal hanya dilakukan oleh mahasiswa Fakultas Ilmu Komputer Universitas Indonesia.</i></p>
                        </div>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><h1>Lokasi</h1></li>
                        <li class="list-group-item">Fakultas Ilmu Komputer.</li>
                        <li class="list-group-item">Kampus UI Depok, Pondok Cina, Kecamatan Beji, Kota Depok, Jawa Barat 16424</li>
                        <li class="list-group-item">(021) 7863419</li>
                    </ul>
                </div>
                <div class="col-md-6">
                    <form action="" method="POST" class="ml-5">
                        {% csrf_token %}
                        {{ formulir }}
                        <div class = "centre-items" style = "margin-top: 2%">
                            <input type = "submit" class="btn btn-primary" value="Submit"> 
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    
    <section class="cekjadwal" id="cekjadwal">
        <div class="table-responsive" id="Table">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Nama Mata Kuliah</th>
                        <th scope="col">Nama Dosen</th>
                        <th scope="col">Jumlah SKS</th>
                        <th scope="col">Deskripsi Mata Kuliah</th>
                        <th scope="col">Tahun Semester</th>
                        <th scope="col">Ruang Kelas</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                {% for i in jadwal_ku %}
                <tbody>
                    <tr>
                        <td>{{i.nama_mata_kuliah}}</td>
                        <td>{{i.nama_dosen}}</td>
                        <td>{{i.jumlah_sks}}</td>
                        <td>{{i.deskripsi_mata_kuliah}}</td>
                        <td>{{i.tahun_semester}}</td>
                        <td>{{i.ruang_kelas}}</td>
                        <td><a  href = "{% url 'jadwal:detail' pk=i.pk %}"><button class="btn btn-icon btn-danger">Detail</button></a></td>
                        <td><a  href = "{% url 'jadwal:hapus' pk=i.pk %}"><button class="btn btn-icon btn-danger">Delete</button></a></td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
    </section>

    <div class="footer">
        <p>Copyright @ 2020 Dzaky</p>
      </div>
</body>
</html>